#define SECRET_SSID "aquasharp"
#define SECRET_PASS "aqua2023"
#define SECRET_BROKER "mqtt-aquasharp-westeu-dev-001.azure-devices.net"
#define SECRET_USERNAME "mqtt-aquasharp-westeu-dev-001.azure-devices.net/AquaSharp_mkr_1/?api-version=2018-06-30"
#define SECRET_PASSWORD "SharedAccessSignature sr=mqtt-aquasharp-westeu-dev-001.azure-devices.net%2Fdevices%2FAquaSharp_mkr_1&sig=PxMWfxExfwXPcbvSJGEkLuXN5qroXaDhB54X%2BqGU%2Fd4%3D&se=1689441251"
#define SECRET_DEVICEID "AquaSharp_mkr_1"
